name: bronco_bond
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  autoscale_tabbarview: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_slidable: null
  google_fonts: ^6.1.0
  http: null
  image_picker: ^1.0.7
  jwt_decoder: null
  shared_preferences: null
  socket_io_client: ^3.0.0-beta.2
  table_calendar: ^3.0.9
  intl: 0.18.1
  flutter_week_view: ^1.3.0
  sliding_up_panel: ^2.0.0+1
  velocity_x: null
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.7
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/BroncoBondAppLogo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/BroncoBond_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/BroncoBond_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/BroncoBond_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/BroncoBond_logo.png"

flutter_native_splash:
  color: "3B5F43"
  image: "assets/images/BroncoBondCircle.png"
  android: true
  ios: true
