const List<String> majors = [
  "Aerospace Engineering",
  "Agribusiness and Food Industry Management",
  "Agricultural Science",
  "Animal Health Science",
  "Animal Science",
  "Anthropology",
  "Apparel Merchandising and Management",
  "Architecture",
  "Art History",
  "Biology",
  "Biotechnology",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Communication",
  "Computer Engineering",
  "Computer Science",
  "Construction Engineering and Management",
  "Criminology",
  "Early Childhood Studies",
  "Economics",
  "Electrical Engineering",
  "Electromechanical Systems Engineering Technology",
  "Electronic Systems Engineering Technology",
  "English",
  "Environmental Biology",
  "Food Science and Technology",
  "Gender, Ethnicity, and Multicultural Studies",
  "Geography",
  "Geology",
  "History",
  "Hospitality Management",
  "Industrial Engineering",
  "Kinesiology",
  "Landscape Architecture",
  "Liberal Studies",
  "Manufacturing Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Music",
  "Nutrition",
  "Philosophy",
  "Physics",
  "Plant Science",
  "Political Science",
  "Psychology",
  "Science, Technology, and Society",
  "Sociology",
  "Spanish",
  "Theatre",
  "Urban and Regional Planning",
  "Visual Communication Design",
]; // List of majors (implement later)

const List<String> minors = [
  "Accounting",
  "African American Studies",
  "Agribusiness and Food Industry Management",
  "Agronomy",
  "Animal and Veterinary Science",
  "Anthropology",
  "Art History",
  "Asian/Pacific Islander American Studies",
  "Astronomy",
  "Biophysics",
  "Botany",
  "Business Law",
  "Business",
  "Chemistry",
  "Chicana/o and Latina/o Studies",
  "Chinese",
  "Communication Studies",
  "Computer Information Systems",
  "Computer Science",
  "Contract Management",
  "Criminology",
  "Culinology",
  "Dance",
  "Data Science",
  "Economics",
  "Energy Engineering",
  "English",
  "Entrepreneurship",
  "Environmental Health Specialist",
  "Equine Studies",
  "Fashion Merchandising",
  "Finance",
  "Food Safety",
  "Food Science and Technology",
  "Footwear Design and Merchandising",
  "French",
  "Gender and Sexuality Studies",
  "Geographic Information Systems",
  "Geography",
  "Geology",
  "History",
  "Horticulture",
  "Hospitality Management",
  "Human Resources",
  "International Agricultural Business Management",
  "International Business",
  "Landscape Architecture",
  "Management and Leadership",
  "Management of Not-for-Profit Organization",
  "Marketing Management",
  "Materials Engineering",
  "Mathematics",
  "Microbiology",
  "Multicultural Leadership Studies",
  "Multimedia Journalism",
  "Music",
  "Native American Studies",
  "Nonviolence Studies",
  "Nutrition",
  "Operations Management",
  "Pest and Disease Management",
  "Philosophy",
  "Physics",
  "Physiology",
  "Plant Based Food and Nutrition",
  "Political Science",
  "Psychology",
  "Public Relations",
  "Real Estate",
  "Regenerative Studies",
  "Science Education",
  "Science, Technology, and Society",
  "Social Work",
  "Sociology",
  "Soil Science",
  "Spanish",
  "Statistics",
  "Studio Arts",
  "Supply Chain/Logistics",
  "Teaching English to Speakers of Other Languages",
  "Theatre",
  "Urban and Community Agriculture",
  "Urban and Regional Planning",
  "Water Resources and Irrigation Design",
  "Writing Studies",
  "Zoology",
]; // List of minors (implement later)

const List<String> years = [
  "2034",
  "2033",
  "2032",
  "2031",
  "2030",
  "2029",
  "2028",
  "2027",
  "2026",
  "2025",
  "2024",
  "2023",
  "2022",
  "2021",
  "2020",
  "2019",
  "2018",
  "2017",
  "2016",
  "2015",
  "2014",
  "2013",
  "2012",
  "2011",
  "2010",
  "2009",
  "2008",
  "2007",
  "2006",
  "2005",
  "2004",
  "2003",
  "2002",
  "2001",
  "2000",
  "1999",
  "1998",
  "1997",
  "1996",
  "1995",
  "1994",
  "1993",
  "1992",
  "1991",
  "1990",
  "1989",
  "1988",
  "1987",
  "1986",
  "1985",
  "1984",
  "1983",
  "1982",
  "1981",
  "1980"
];
