name: CICD

on:
  push:
    branches:
      - aws-test-Jay

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Set Environment Variables
        run: |
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "JWT_KEY=${{ secrets.JWT_KEY }}" >> $GITHUB_ENV
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> $GITHUB_ENV
          echo "WEBSITES_PORT=${{ secrets.WEBSITES_PORT }}" >> $GITHUB_ENV
          echo "AUTH_PASS=${{ secrets.AUTH_PASS }}" >> $GITHUB_ENV
          echo "AUTH_EMAIL=${{ secrets.AUTH_EMAIL }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Generate Deployment Package
        run: zip -r broncobond-build.zip .

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'BroncoBondApp'
          environment_name: 'BroncoBondEnv'
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: broncobond-build.zip
