name: CICD

on:
  push:
    branches:
      - BroncoBond-Main
    paths:
      - 'backends/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install Dependencies
        working-directory: backends  # Ensure npm install happens in the backends folder
        run: npm install

      - name: Run Build Script
        working-directory: backends  # Ensure npm build runs in the backends folder
        run: npm run build

      - name: Set Environment Variables
        run: |
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "JWT_KEY=${{ secrets.JWT_KEY }}" >> $GITHUB_ENV
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> $GITHUB_ENV
          echo "WEBSITES_PORT=${{ secrets.WEBSITES_PORT }}" >> $GITHUB_ENV
          echo "AUTH_PASS=${{ secrets.AUTH_PASS }}" >> $GITHUB_ENV
          echo "AUTH_EMAIL=${{ secrets.AUTH_EMAIL }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Generate Deployment Package
        working-directory: backends  # Ensure we zip files in the backends folder
        run: zip -r broncobond-build.zip . -x "*.git*" "node_modules/*"

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v22
        
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'BroncoBond-App'
          environment_name: 'BroncoBond-Env'
          version_label: ${{ github.sha }}
          region: us-west-1
          deployment_package: broncobond-build.zip
